import { resolve } from 'node:path'
import { defineConfig } from 'electron-vite'
import react from '@vitejs/plugin-react'
import { writeNotices } from './scripts/licenses.mjs'

const shared = resolve(__dirname, 'src/shared')
const server = resolve(__dirname, 'src/server')
/** Loopback port the dev server proxies /api and /ws to (the server inside Electron listens here in dev). */
const DEV_API_PORT = Number(process.env.VESPER_PORT || 41730)
/**
 * Test hooks, /api/test/* and every VESPER_* test switch are compiled in only when this is true (07 B10). Dev and e2e
 * builds: true. The release build (npm run dist) sets VESPER_BUILD_TEST=0, and the code is dead-code-eliminated.
 */
const TEST_BUILD = process.env.VESPER_BUILD_TEST !== '0'
const define = { __VESPER_TEST__: JSON.stringify(TEST_BUILD) }
/**
 * Output root (default out/). `VESPER_OUT_DIR` builds elsewhere, so the release-build check
 * (scripts/check-release.mjs) never overwrites the test build that e2e runs use.
 */
const OUT = process.env.VESPER_OUT_DIR ? resolve(process.env.VESPER_OUT_DIR) : resolve(__dirname, 'out')

/**
 * THIRD_PARTY_NOTICES.txt (07 E7): generated by scripts/licenses.mjs after the renderer is built, into the web root
 * (served at /THIRD_PARTY_NOTICES.txt) and next to it at <out>/THIRD_PARTY_NOTICES.txt (electron-builder ships that
 * one next to the exe, extraFiles).
 */
const notices = {
  name: 'vesper:third-party-notices',
  apply: 'build' as const,
  closeBundle: async () => {
    await writeNotices({ root: __dirname, outFiles: [resolve(OUT, 'web', 'THIRD_PARTY_NOTICES.txt'), resolve(OUT, 'THIRD_PARTY_NOTICES.txt')] })
  }
}

/**
 * electron-vite forces base './' for production renderer builds (it assumes file://). Vesper's client is always served
 * over HTTP by its own server, and deep links (/s/<uid>) need root-absolute /assets URLs; a <base> tag is not an option
 * because the CSP sets base-uri 'none'. This runs after electron-vite's preset and puts the base back to '/'.
 */
const rootBase = { name: 'vesper:root-base', enforce: 'post' as const, config: () => ({ base: '/' }) }

export default defineConfig({
  main: {
    define,
    resolve: { alias: { '@shared': shared, '@server': server } },
    build: {
      outDir: resolve(OUT, 'main'),
      rollupOptions: {
        input: {
          index: resolve(__dirname, 'src/main/index.ts'),
          // The same server without Electron (browser e2e, headless use): node out/main/server-node.js
          'server-node': resolve(__dirname, 'src/server/node-entry.ts'),
          'db.worker': resolve(__dirname, 'src/workers/db.worker.ts'),
          'stt.process': resolve(__dirname, 'src/workers/stt.process.ts'),
          'extract.process': resolve(__dirname, 'src/workers/extract.process.ts')
        },
        output: {
          entryFileNames: '[name].js',
          chunkFileNames: 'chunks/[name]-[hash].js'
        }
      }
    }
  },
  preload: {
    define,
    resolve: { alias: { '@shared': shared } },
    build: { outDir: resolve(OUT, 'preload') }
  },
  renderer: {
    root: resolve(__dirname, 'src/web'),
    base: '/',
    define,
    resolve: { alias: { '@shared': shared, '@web': resolve(__dirname, 'src/web') } },
    plugins: [react(), rootBase, notices],
    // Module workers, so the code highlighter's worker can lazy-load grammars as separate chunks (07 D7; ui-kit).
    worker: { format: 'es' },
    server: {
      // In dev the window loads the Vite server; API and WebSocket go to the real server in the Electron main process.
      proxy: {
        '/api': { target: `http://127.0.0.1:${DEV_API_PORT}`, changeOrigin: false },
        '/ws': { target: `ws://127.0.0.1:${DEV_API_PORT}`, ws: true, changeOrigin: false }
      }
    },
    build: {
      outDir: resolve(OUT, 'web'),
      emptyOutDir: true,
      chunkSizeWarningLimit: 2500,
      minify: 'esbuild',
      rollupOptions: { input: resolve(__dirname, 'src/web/index.html') }
    }
  }
})
