/**
 * Runtime copy of each endpoint's auth level (07 B2). The mapped type makes it exhaustive and exact: a new or changed
 * entry in shared/api.ts `Endpoints` fails to compile here until this table agrees.
 */
import type { EndpointKey, Endpoints } from '@shared/api'

export const ENDPOINT_AUTH: { readonly [K in EndpointKey]: Endpoints[K]['auth'] } = {
  'GET /api/auth/state': 'public',
  'POST /api/auth/login': 'public',
  'POST /api/auth/logout': 'device',
  'POST /api/auth/sudo': 'device',
  'POST /api/auth/password': 'device',
  'GET /api/auth/devices': 'device',
  'DELETE /api/auth/devices/:id': 'sudo',
  'POST /api/auth/devices/:id/approve': 'desktop',
  'GET /api/auth/log': 'sudo',
  'POST /api/auth/pair': 'desktop',
  'POST /api/auth/pair/redeem': 'public',
  'GET /api/bootstrap': 'device',
  'GET /api/settings': 'device',
  'PATCH /api/settings': 'device',
  'PUT /api/secrets/:name': 'desktop',
  'DELETE /api/secrets/:name': 'desktop',
  'GET /api/protocols': 'device',
  'PUT /api/protocols': 'desktop',
  'POST /api/protocols/reset': 'desktop',
  'GET /api/sessions': 'device',
  'POST /api/sessions': 'device',
  'GET /api/sessions/:uid': 'device',
  'PATCH /api/sessions/:uid': 'device',
  'DELETE /api/sessions/:uid': 'device',
  'POST /api/sessions/:uid/restore': 'device',
  'POST /api/sessions/:uid/epoch': 'device',
  'PUT /api/sessions/:uid/links/:shortId': 'device',
  'DELETE /api/sessions/:uid/links/:shortId': 'device',
  'POST /api/trash/empty': 'device',
  'GET /api/sessions/:uid/messages': 'device',
  'GET /api/sessions/:uid/timeline': 'device',
  'GET /api/sessions/:uid/variants/:seq': 'device',
  'POST /api/sessions/:uid/variants/:seq': 'device',
  'GET /api/messages/:uid/locate': 'device',
  'DELETE /api/messages/:uid': 'device',
  'GET /api/messages/:uid/recalled': 'device',
  'POST /api/messages/:uid/restore': 'device',
  'GET /api/search': 'device',
  'GET /api/memory/status': 'device',
  'POST /api/memory/recall': 'device',
  'POST /api/memory/reindex': 'sudo',
  'POST /api/memory/backfill': 'device',
  'GET /api/memory/backfill/estimate': 'device',
  'GET /api/memory/manifest': 'device',
  'DELETE /api/memory/messages/:uid': 'device',
  'DELETE /api/memory/index': 'sudo',
  'GET /api/memory/timeline': 'device',
  'GET /api/facts': 'device',
  'POST /api/facts': 'device',
  'PATCH /api/facts/:id': 'device',
  'DELETE /api/facts/:id': 'device',
  'GET /api/prompts': 'device',
  'POST /api/prompts': 'device',
  'PATCH /api/prompts/:id': 'device',
  'DELETE /api/prompts/:id': 'device',
  'POST /api/attachments': 'device',
  'GET /api/attachments/:sha': 'device',
  'GET /api/attachments/:sha/text': 'device',
  'GET /api/providers/presets': 'device',
  'POST /api/providers/llm/test': 'desktop',
  'GET /api/providers/llm/models': 'device',
  'POST /api/providers/voyage/test': 'desktop',
  'POST /api/providers/tts/test': 'desktop',
  'POST /api/providers/stt/test': 'desktop',
  'GET /api/tts/voices': 'device',
  'GET /api/tts/preview/:provider/:voiceId': 'device',
  'POST /api/tts/sample': 'device',
  'GET /api/stt/models': 'device',
  'POST /api/stt/models/:id/download': 'desktop',
  'DELETE /api/stt/models/:id': 'desktop',
  'POST /api/stt/unload': 'device',
  'GET /api/network': 'device',
  'PUT /api/network': 'desktop',
  'POST /api/network/firewall/allow': 'desktop',
  'POST /api/network/tailscale/serve': 'desktop',
  'GET /api/export': 'sudo',
  'POST /api/import': 'sudo',
  'POST /api/backup': 'sudo',
  'GET /api/backups': 'sudo',
  'POST /api/backups/restore': 'desktop',
  'GET /api/data/usage': 'device',
  'GET /api/system/resources': 'device',
  'POST /api/system/open-folder': 'desktop',
  'POST /api/system/unload-voice': 'device',
  'GET /api/system/update': 'device',
  'POST /api/system/update/check': 'desktop',
  'POST /api/system/update/download': 'desktop',
  'POST /api/system/update/restart': 'desktop'
}

export const ENDPOINT_KEYS = Object.keys(ENDPOINT_AUTH) as EndpointKey[]
