/**
 * Settings → About: version, updates (H-v12-updates: UpdatesGroup), the design notes (07 A1: docs/OWNER-NOTES.md), credits and licences (07 E7, incl. the
 * GPL-3.0 note for espeak-ng inside sherpa-onnx), the full third-party notice when the build ships one, and — on the
 * desktop — the data and log folders (POST /api/system/open-folder).
 */
import { lazy, Suspense, useEffect, useState, type ReactNode } from 'react'
import { BookOpen, FileText, FolderOpen } from 'lucide-react'
import { SILERO_VAD, STT_MODELS } from '@shared/models'
import { Badge } from '../../../components/Badge'
import { Button } from '../../../components/Button'
import { Callout } from '../../../components/Callout'
import { Dialog } from '../../../components/Dialog'
import { Spinner } from '../../../components/Spinner'
import { StarGlyph } from '../../../app/StarGlyph'
import { useStore } from '../../../lib/store'
import { openFolder } from '../folders'
import type { SettingsSectionProps } from '../sections'
import { ExternalLink, SettingRow, SettingsAdvanced, SettingsGroup, SettingsPageHeader } from '../ui'
import { UpdatesGroup } from './UpdatesGroup'

const DesignNotes = lazy(() => import('./DesignNotes'))

interface Credit {
  name: string
  what: string
  licence: string
  href: string
}

const SOFTWARE: Credit[] = [
  { name: 'Electron', what: 'The desktop window', licence: 'MIT', href: 'https://www.electronjs.org' },
  { name: 'React', what: 'The interface', licence: 'MIT', href: 'https://react.dev' },
  { name: 'three.js · React Three Fiber · drei', what: 'The Star', licence: 'MIT', href: 'https://threejs.org' },
  { name: 'Fastify', what: 'The server inside Vesper', licence: 'MIT', href: 'https://fastify.dev' },
  { name: 'sherpa-onnx', what: 'Speech recognition engine', licence: 'Apache-2.0', href: 'https://github.com/k2-fsa/sherpa-onnx' },
  { name: 'ONNX Runtime', what: 'Runs the speech models', licence: 'MIT', href: 'https://onnxruntime.ai' },
  { name: 'espeak-ng', what: 'Inside sherpa-onnx (statically linked)', licence: 'GPL-3.0', href: 'https://github.com/espeak-ng/espeak-ng' },
  { name: 'react-markdown · remark · KaTeX', what: 'Messages, tables and maths', licence: 'MIT', href: 'https://github.com/remarkjs/react-markdown' },
  { name: 'Shiki', what: 'Code highlighting', licence: 'MIT', href: 'https://shiki.style' },
  { name: 'Lucide', what: 'Icons', licence: 'ISC', href: 'https://lucide.dev' },
  { name: 'Inter · JetBrains Mono', what: 'Typefaces', licence: 'OFL-1.1', href: 'https://rsms.me/inter/' }
]

/** Bundled-model credits come from the model catalogue (attribution text required by CC-BY, 07 E7). */
const MODELS: Credit[] = [
  ...STT_MODELS.map((m) => ({ name: m.label.replace(/\s*\(.*\)$/, ''), what: m.attribution, licence: m.license.startsWith('Model licence') ? 'See model card' : m.license, href: 'https://github.com/k2-fsa/sherpa-onnx' })),
  { name: 'Silero VAD (bundled)', what: SILERO_VAD.attribution, licence: SILERO_VAD.license, href: 'https://github.com/snakers4/silero-vad' }
]

/**
 * The full third-party notice (THIRD_PARTY_NOTICES.txt at the repository root, generated by scripts/licenses.mjs for
 * release builds, 07 E7). It is bundled at build time when the file exists — as its own chunk, loaded only when the
 * dialog opens — so a build without it never asks the server for a missing file (no 404); it then says where the
 * installed app keeps it.
 */
const NOTICE_FILES = import.meta.glob<string>('../../../../../THIRD_PARTY_NOTICES.txt', { query: '?raw', import: 'default' })
const loadNotice = Object.values(NOTICE_FILES)[0] ?? null

function NoticeText(): ReactNode {
  const [text, setText] = useState<string | null>(null)
  const [missing, setMissing] = useState(loadNotice === null)
  useEffect(() => {
    if (!loadNotice) return
    let alive = true
    loadNotice().then(
      (t) => {
        if (alive) setText(t)
      },
      () => {
        if (alive) setMissing(true)
      }
    )
    return () => {
      alive = false
    }
  }, [])
  if (missing) return <p>This build doesn't include the full notice. The installed app keeps it as THIRD_PARTY_NOTICES.txt next to Vesper.exe.</p>
  if (text === null) return <Spinner label="Loading the notice" />
  return (
    <pre className="notice-text" tabIndex={0}>
      {text}
    </pre>
  )
}

function CreditList({ items, label }: { items: Credit[]; label: string }): ReactNode {
  return (
    <ul className="credits" aria-label={label}>
      {items.map((c) => (
        <li key={c.name}>
          <span className="credits__name">
            <ExternalLink href={c.href}>{c.name}</ExternalLink>
          </span>
          <span className="credits__what">{c.what}</span>
          <span className="credits__lic">
            <Badge tone={c.licence.startsWith('GPL') ? 'warning' : 'neutral'}>{c.licence}</Badge>
          </span>
        </li>
      ))}
    </ul>
  )
}

export default function SettingsAbout({ advanced }: SettingsSectionProps): ReactNode {
  const b = useStore((s) => s.bootstrap)
  const [notesOpen, setNotesOpen] = useState(false)
  const [opening, setOpening] = useState<string | null>(null)
  const [noticeOpen, setNoticeOpen] = useState(false)
  const desktop = b?.desktop ?? false

  const open = async (which: 'roaming' | 'logs'): Promise<void> => {
    setOpening(which)
    await openFolder(which)
    setOpening(null)
  }

  return (
    <div className="spage">
      <SettingsPageHeader title="About" />

      <SettingsGroup>
        <div className="about-hero">
          <StarGlyph size={48} />
          <div>
            <p className="about-hero__name">Vesper</p>
            <p className="about-hero__meta">
              Version <span className="tabular">{b?.version ?? '—'}</span>
              {b?.portable ? ' · portable' : ''} · An AI companion that lives on your PC
            </p>
          </div>
        </div>
        <SettingRow inline>
          <div className="set-row__text">
            <span className="set-row__label">Design notes</span>
            <span className="set-row__desc">What you asked for, what Vesper does, and why — including where it differs and what only your own keys can confirm.</span>
          </div>
          <Button icon={<BookOpen />} onClick={() => setNotesOpen(true)}>
            Read the notes
          </Button>
        </SettingRow>
      </SettingsGroup>

      <UpdatesGroup />

      {desktop && b?.dataPaths ? (
        <SettingsGroup title="Folders" description="Everything Vesper keeps lives in these two folders on this PC.">
          <SettingRow inline>
            <div className="set-row__text">
              <span className="set-row__label">Your data</span>
              <span className="set-row__desc mono">{b.dataPaths.roaming}</span>
            </div>
            <Button icon={<FolderOpen />} loading={opening === 'roaming'} onClick={() => void open('roaming')}>
              Open folder
            </Button>
          </SettingRow>
          <SettingRow inline>
            <div className="set-row__text">
              <span className="set-row__label">Models, logs and caches</span>
              <span className="set-row__desc mono">{b.dataPaths.local}</span>
            </div>
            <Button icon={<FolderOpen />} loading={opening === 'logs'} onClick={() => void open('logs')}>
              Open folder
            </Button>
          </SettingRow>
        </SettingsGroup>
      ) : null}

      <SettingsGroup title="Made with" description="Vesper stands on these open-source projects." actions={
          <Button size="sm" variant="ghost" icon={<FileText />} onClick={() => setNoticeOpen(true)}>
            Full licence notice
          </Button>
        }>
        <CreditList items={SOFTWARE} label="Software" />
      </SettingsGroup>

      <SettingsGroup title="Speech models" description="Downloaded on request; each keeps its own licence.">
        <CreditList items={MODELS} label="Models" />
      </SettingsGroup>

      <SettingsAdvanced open={advanced} summary="Technical details">
        <SettingsGroup>
          <dl className="skv">
            <dt>Version</dt>
            <dd className="tabular">{b?.version ?? '—'}</dd>
            <dt>This device</dt>
            <dd>
              {b?.device.name ?? '—'} · {b?.device.kind ?? '—'}
            </dd>
            <dt>Connected through</dt>
            <dd>{b?.device.listener === 'loopback' ? 'This PC' : b?.device.listener === 'lan' ? 'Local network (HTTPS)' : b?.device.listener === 'tailnet' ? 'Tailscale' : '—'}</dd>
            <dt>Device ID</dt>
            <dd className="mono">{b?.device.id ?? '—'}</dd>
            {b?.secretsInvalid.length ? (
              <>
                <dt>Keys to re-enter</dt>
                <dd>{b.secretsInvalid.join(', ')}</dd>
              </>
            ) : null}
          </dl>
        </SettingsGroup>
      </SettingsAdvanced>

      <Callout tone="info" icon={<FileText />} title="Free software">
        Vesper is open source under the GNU General Public License v3.0 (GPL-3.0): you may use, study, change and share it, and
        changes you share must stay under the same licence. Its speech engine includes espeak-ng, which is GPL-3.0 too.
      </Callout>

      <Dialog open={noticeOpen} onClose={() => setNoticeOpen(false)} title="Third-party licences" size="lg">
        {noticeOpen ? <NoticeText /> : null}
      </Dialog>
      <Dialog open={notesOpen} onClose={() => setNotesOpen(false)} title="Design notes" description="What you asked for, what Vesper does, and why." size="lg">
        <Suspense fallback={<Spinner label="Loading the notes" />}>{notesOpen ? <DesignNotes /> : null}</Suspense>
      </Dialog>
    </div>
  )
}
